/* ============================================
   CRUST & CHILLY — SHARED DATA
   ============================================ */

const PHONE = '917487980840';
const VERSION = '4.0';

const ITEMS = [
{id:1,n:'Crust Crunch Burger',c:'burgers',p:149,op:199,d:'Double patty, smoky sauce, cheese & onion rings',r:4.9,rc:324,tag:'Bestseller',sp:2,e:'🍔',bg:'#FFE8D6'},
{id:2,n:'Classic Cheese Burger',c:'burgers',p:119,op:0,d:'Patty, cheddar, lettuce, tomato',r:4.7,rc:189,tag:'Popular',sp:1,e:'🍔',bg:'#FFF3E0'},
{id:3,n:'Paneer Tikka Burger',c:'burgers',p:139,op:0,d:'Grilled paneer tikka, mint mayo',r:4.6,rc:203,tag:'',sp:2,e:'🍔',bg:'#E8F5E9'},
{id:4,n:'Spicy Aloo Burger',c:'burgers',p:89,op:0,d:'Crispy aloo tikki with spicy chutney',r:4.5,rc:278,tag:'',sp:2,e:'🍔',bg:'#FFFDE7'},
{id:5,n:'Mushroom Swiss Burger',c:'burgers',p:169,op:0,d:'Sautéed mushrooms, swiss cheese',r:4.7,rc:134,tag:'',sp:1,e:'🍔',bg:'#FFF8E1'},
{id:6,n:'BBQ Crunch Burger',c:'burgers',p:159,op:0,d:'BBQ sauce, caramelized onions, cheddar',r:4.8,rc:156,tag:'New',sp:1,e:'🍔',bg:'#FBE9E7'},
{id:7,n:'Veggie Supreme',c:'burgers',p:129,op:0,d:'Mixed veggie patty, avocado, sprouts',r:4.6,rc:167,tag:'',sp:1,e:'🍔',bg:'#E8F5E9'},
{id:8,n:'Mexican Burger',c:'burgers',p:149,op:0,d:'Beans patty, jalapeños, salsa',r:4.7,rc:198,tag:'',sp:3,e:'🍔',bg:'#FFEBEE'},
{id:9,n:'Peri Peri Burger',c:'burgers',p:159,op:0,d:'Peri peri patty, roasted peppers',r:4.8,rc:112,tag:'Popular',sp:3,e:'🍔',bg:'#FCE4EC'},
{id:10,n:'Double Trouble',c:'burgers',p:199,op:259,d:'Two patties, double cheese',r:4.9,rc:89,tag:'New',sp:2,e:'🍔',bg:'#FFF3E0'},
{id:11,n:'Corn & Bean Burger',c:'burgers',p:109,op:0,d:'Sweet corn & black bean patty',r:4.4,rc:145,tag:'',sp:1,e:'🍔',bg:'#F1F8E9'},
{id:12,n:'Tandoori Paneer Burger',c:'burgers',p:149,op:0,d:'Tandoori paneer, raita, pickled onion',r:4.8,rc:245,tag:'Bestseller',sp:2,e:'🍔',bg:'#FFCCBC'},
{id:13,n:'Spicy Paneer Wrap',c:'wraps',p:129,op:0,d:'Grilled paneer, spicy mayo in tortilla',r:4.8,rc:212,tag:'Popular',sp:2,e:'🌯',bg:'#E8F5E9'},
{id:14,n:'Veg Frankie Roll',c:'wraps',p:99,op:0,d:'Mixed veggie filling with chutney',r:4.5,rc:178,tag:'',sp:2,e:'🌯',bg:'#FFFDE7'},
{id:15,n:'Tandoori Paneer Roll',c:'wraps',p:139,op:0,d:'Tandoori paneer, mint chutney',r:4.7,rc:134,tag:'',sp:2,e:'🌯',bg:'#FCE4EC'},
{id:16,n:'Falafel Wrap',c:'wraps',p:139,op:0,d:'Crispy falafel, hummus, tahini',r:4.7,rc:98,tag:'New',sp:1,e:'🌯',bg:'#E8EAF6'},
{id:17,n:'Mushroom Cheese Roll',c:'wraps',p:129,op:0,d:'Mushrooms with melted cheese & herbs',r:4.5,rc:87,tag:'',sp:1,e:'🌯',bg:'#EFEBE9'},
{id:18,n:'Mexican Bean Wrap',c:'wraps',p:119,op:0,d:'Spicy beans, corn, cheese, salsa',r:4.6,rc:156,tag:'Popular',sp:2,e:'🌯',bg:'#FFEBEE'},
{id:19,n:'Schezwan Paneer Roll',c:'wraps',p:139,op:0,d:'Paneer in schezwan sauce',r:4.8,rc:234,tag:'Bestseller',sp:3,e:'🌯',bg:'#FBE9E7'},
{id:20,n:'Garden Fresh Wrap',c:'wraps',p:99,op:0,d:'Grilled veggies, hummus & greens',r:4.4,rc:112,tag:'',sp:1,e:'🌯',bg:'#E8F5E9'},
{id:21,n:'Chilly Cheese Fries',c:'fries',p:119,op:0,d:'Loaded fries, cheese, chilly flakes',r:4.9,rc:456,tag:'Must Try',sp:2,e:'🍟',bg:'#FFF9C4'},
{id:22,n:'Classic Salted Fries',c:'fries',p:69,op:0,d:'Golden fries with sea salt',r:4.5,rc:567,tag:'',sp:1,e:'🍟',bg:'#FFFDE7'},
{id:23,n:'Peri Peri Fries',c:'fries',p:99,op:0,d:'Fries in fiery peri peri seasoning',r:4.7,rc:234,tag:'',sp:3,e:'🍟',bg:'#FFEBEE'},
{id:24,n:'Loaded Nachos Fries',c:'fries',p:149,op:0,d:'Fries with nachos & jalapeños',r:4.8,rc:189,tag:'New',sp:2,e:'🍟',bg:'#FFF3E0'},
{id:25,n:'Garlic Butter Fries',c:'fries',p:89,op:0,d:'Fries in garlic butter with parmesan',r:4.6,rc:145,tag:'',sp:1,e:'🍟',bg:'#F1F8E9'},
{id:26,n:'Masala Magic Fries',c:'fries',p:79,op:0,d:'Indian spice fries with chaat masala',r:4.7,rc:312,tag:'Popular',sp:2,e:'🍟',bg:'#FCE4EC'},
{id:27,n:'Club Grilled Sandwich',c:'sandwiches',p:109,op:139,d:'Triple-layer grilled with cheese',r:4.7,rc:178,tag:'New',sp:1,e:'🥪',bg:'#FFF3E0'},
{id:28,n:'Paneer Tikka Sandwich',c:'sandwiches',p:119,op:0,d:'Grilled paneer tikka, bell peppers',r:4.6,rc:145,tag:'',sp:2,e:'🥪',bg:'#FCE4EC'},
{id:29,n:'Cheese Corn Sandwich',c:'sandwiches',p:99,op:0,d:'Sweet corn, cheese, mayo on multigrain',r:4.5,rc:123,tag:'',sp:1,e:'🥪',bg:'#FFF9C4'},
{id:30,n:'Bombay Masala Toast',c:'sandwiches',p:79,op:0,d:'Potato, beetroot, chutney & cheese',r:4.8,rc:389,tag:'Popular',sp:2,e:'🥪',bg:'#E8F5E9'},
{id:31,n:'Mushroom Melt Sandwich',c:'sandwiches',p:109,op:0,d:'Mushrooms, onions, swiss cheese',r:4.6,rc:98,tag:'',sp:1,e:'🥪',bg:'#EFEBE9'},
{id:32,n:'Veg Mayo Sandwich',c:'sandwiches',p:69,op:0,d:'Fresh veggies with creamy mayo',r:4.3,rc:234,tag:'',sp:1,e:'🥪',bg:'#E8F5E9'},
{id:33,n:'Mexican Grilled Sandwich',c:'sandwiches',p:129,op:0,d:'Beans, jalapeños, corn, cheese, salsa',r:4.7,rc:112,tag:'New',sp:3,e:'🥪',bg:'#FFEBEE'},
{id:34,n:'Chocolate Sandwich',c:'sandwiches',p:79,op:0,d:'Warm chocolate with banana',r:4.4,rc:198,tag:'',sp:1,e:'🥪',bg:'#EFEBE9'},
{id:35,n:'Pesto Veggie Sandwich',c:'sandwiches',p:119,op:0,d:'Basil pesto, zucchini, mozzarella',r:4.7,rc:89,tag:'',sp:1,e:'🥪',bg:'#E8F5E9'},
{id:36,n:'Spicy Aloo Sandwich',c:'sandwiches',p:89,op:0,d:'Spiced potato with chutney',r:4.5,rc:267,tag:'Popular',sp:2,e:'🥪',bg:'#FFF3E0'},
{id:37,n:'Masala Tikka Pav',c:'tikka-pav',p:99,op:0,d:'Spicy tikka masala with butter pav',r:4.9,rc:389,tag:'Bestseller',sp:3,e:'🌭',bg:'#FCE4EC'},
{id:38,n:'Cheese Tikka Pav',c:'tikka-pav',p:119,op:0,d:'Tikka with melted cheese on pav',r:4.8,rc:267,tag:'Popular',sp:2,e:'🌭',bg:'#FFF3E0'},
{id:39,n:'Paneer Tikka Pav',c:'tikka-pav',p:129,op:0,d:'Grilled paneer in rich gravy',r:4.7,rc:178,tag:'',sp:2,e:'🌭',bg:'#E8F5E9'},
{id:40,n:'Mushroom Tikka Pav',c:'tikka-pav',p:119,op:0,d:'Mushrooms in creamy tikka',r:4.5,rc:89,tag:'New',sp:2,e:'🌭',bg:'#EFEBE9'},
{id:41,n:'Special Mix Tikka Pav',c:'tikka-pav',p:139,op:0,d:'Paneer, mushroom & veggies',r:4.8,rc:198,tag:'',sp:2,e:'🌭',bg:'#FFF8E1'},
{id:42,n:'Schezwan Tikka Pav',c:'tikka-pav',p:109,op:0,d:'Fiery schezwan tikka',r:4.6,rc:156,tag:'',sp:3,e:'🌭',bg:'#FFEBEE'},
{id:43,n:'Jain Tikka Pav',c:'tikka-pav',p:99,op:0,d:'No onion no garlic tikka',r:4.5,rc:134,tag:'',sp:1,e:'🌭',bg:'#FFFDE7'},
{id:44,n:'Cheese Garlic Bites',c:'quick-bites',p:89,op:0,d:'Crispy bites with cheese & garlic',r:4.8,rc:267,tag:'Popular',sp:1,e:'🧀',bg:'#E3F2FD'},
{id:45,n:'Veg Spring Rolls',c:'quick-bites',p:99,op:0,d:'Crispy rolls with veggies',r:4.5,rc:189,tag:'',sp:1,e:'🧀',bg:'#E8F5E9'},
{id:46,n:'Corn Cheese Balls',c:'quick-bites',p:109,op:0,d:'Corn & cheese fried balls',r:4.7,rc:156,tag:'',sp:1,e:'🧀',bg:'#FFF9C4'},
{id:47,n:'Paneer Popcorn',c:'quick-bites',p:119,op:0,d:'Bite-sized paneer fried crispy',r:4.7,rc:145,tag:'New',sp:2,e:'🧀',bg:'#FCE4EC'},
{id:48,n:'Onion Rings',c:'quick-bites',p:79,op:0,d:'Thick onion rings, crispy',r:4.4,rc:198,tag:'',sp:1,e:'🧀',bg:'#FFFDE7'},
{id:49,n:'Nachos Grande',c:'quick-bites',p:149,op:0,d:'Loaded nachos with cheese',r:4.8,rc:178,tag:'Popular',sp:2,e:'🧀',bg:'#FFF3E0'},
{id:50,n:'Potato Wedges',c:'quick-bites',p:89,op:0,d:'Seasoned wedges with cream',r:4.5,rc:123,tag:'',sp:1,e:'🧀',bg:'#F1F8E9'},
{id:51,n:'Stuffed Mushrooms',c:'quick-bites',p:129,op:0,d:'Mushrooms with cheese & herbs',r:4.6,rc:98,tag:'',sp:1,e:'🧀',bg:'#EFEBE9'},
{id:52,n:'Crispy Corn',c:'quick-bites',p:99,op:0,d:'Crunchy fried corn, spicy',r:4.7,rc:234,tag:'Must Try',sp:2,e:'🧀',bg:'#FFF9C4'},
{id:53,n:'Coca-Cola',c:'cold-drinks',p:40,op:0,d:'Chilled 300ml',r:4.5,rc:890,tag:'',sp:1,e:'🥤',bg:'#FFEBEE'},
{id:54,n:'Thumbs Up',c:'cold-drinks',p:40,op:0,d:'Chilled 300ml',r:4.4,rc:678,tag:'',sp:1,e:'🥤',bg:'#E3F2FD'},
{id:55,n:'Sprite',c:'cold-drinks',p:40,op:0,d:'Chilled 300ml',r:4.5,rc:567,tag:'',sp:1,e:'🥤',bg:'#E8F5E9'},
{id:56,n:'Fresh Lime Soda',c:'cold-drinks',p:49,op:0,d:'Fresh lime with soda',r:4.7,rc:345,tag:'',sp:1,e:'🥤',bg:'#F1F8E9'},
{id:57,n:'Cold Coffee',c:'cold-drinks',p:79,op:0,d:'Creamy coffee with ice cream',r:4.8,rc:289,tag:'Popular',sp:1,e:'🥤',bg:'#EFEBE9'},
{id:58,n:'Mango Lassi',c:'cold-drinks',p:69,op:0,d:'Thick mango yogurt drink',r:4.6,rc:234,tag:'',sp:1,e:'🥤',bg:'#FFF9C4'},
{id:59,n:'Masala Chaas',c:'cold-drinks',p:39,op:0,d:'Spiced buttermilk with mint',r:4.5,rc:456,tag:'',sp:1,e:'🥤',bg:'#FFFDE7'},
{id:60,n:'Oreo Shake',c:'cold-drinks',p:99,op:0,d:'Thick oreo milkshake',r:4.8,rc:198,tag:'New',sp:1,e:'🥤',bg:'#F3E5F5'},
{id:61,n:'Berry Blast Mocktail',c:'mocktails',p:79,op:0,d:'Berries, soda, lime, mint',r:4.7,rc:198,tag:'',sp:1,e:'🍹',bg:'#F3E5F5'},
{id:62,n:'Virgin Mojito',c:'mocktails',p:89,op:0,d:'Lime, mint, soda, crushed ice',r:4.8,rc:345,tag:'Bestseller',sp:1,e:'🍹',bg:'#E8F5E9'},
{id:63,n:'Blue Lagoon',c:'mocktails',p:99,op:0,d:'Blue curacao, lemon, soda',r:4.6,rc:156,tag:'',sp:1,e:'🍹',bg:'#E3F2FD'},
{id:64,n:'Sunset Cooler',c:'mocktails',p:89,op:0,d:'Orange, grenadine, lime, soda',r:4.7,rc:123,tag:'New',sp:1,e:'🍹',bg:'#FFF3E0'},
{id:65,n:'Watermelon Fizz',c:'mocktails',p:79,op:0,d:'Watermelon, lime, sparkling soda',r:4.5,rc:89,tag:'',sp:1,e:'🍹',bg:'#FCE4EC'},
{id:66,n:'Mango Tango',c:'mocktails',p:99,op:0,d:'Mango, passion fruit, soda',r:4.8,rc:178,tag:'Popular',sp:1,e:'🍹',bg:'#FFF9C4'},
{id:67,n:'Burger Bonanza',c:'combos',p:199,op:289,d:'1 Burger + Fries + Cold Drink',r:4.9,rc:456,tag:'Combo',sp:1,e:'🍽️',bg:'#FFE8D6'},
{id:68,n:'Wrap & Roll Combo',c:'combos',p:349,op:499,d:'Sandwich + Wrap + 2 Mocktails',r:4.8,rc:234,tag:'Combo',sp:1,e:'🍽️',bg:'#E3F2FD'},
{id:69,n:'Family Feast',c:'combos',p:649,op:949,d:'2 Burgers + 2 Tikka Pav + Fries + 4 Drinks',r:4.9,rc:189,tag:'Combo',sp:1,e:'🍽️',bg:'#FFF3E0'},
{id:70,n:'Solo Crunch',c:'combos',p:149,op:199,d:'Burger + Small Fries + Drink',r:4.6,rc:345,tag:'Combo',sp:1,e:'🍽️',bg:'#FFFDE7'},
{id:71,n:'Couple Special',c:'combos',p:449,op:599,d:'2 Burgers + Fries + 2 Mocktails',r:4.8,rc:167,tag:'Combo',sp:1,e:'🍽️',bg:'#FCE4EC'},
{id:72,n:'Chilly Paneer Dry',c:'chilly-specials',p:149,op:0,d:'Crispy paneer in chilly sauce',r:4.8,rc:289,tag:'Bestseller',sp:3,e:'🔥',bg:'#FFEBEE'},
{id:73,n:'Chilly Mushroom',c:'chilly-specials',p:129,op:0,d:'Mushrooms in chilly garlic',r:4.6,rc:145,tag:'',sp:2,e:'🔥',bg:'#EFEBE9'},
{id:74,n:'Chilly Baby Corn',c:'chilly-specials',p:119,op:0,d:'Baby corn in schezwan',r:4.5,rc:123,tag:'',sp:2,e:'🔥',bg:'#FFF9C4'},
{id:75,n:'Chilly Noodles',c:'chilly-specials',p:109,op:0,d:'Noodles in chilly garlic',r:4.6,rc:234,tag:'Popular',sp:2,e:'🔥',bg:'#E8F5E9'},
{id:76,n:'Chilly Cheese Toast',c:'chilly-specials',p:89,op:0,d:'Toast with chilly cheese',r:4.7,rc:167,tag:'',sp:2,e:'🔥',bg:'#FFF3E0'},
{id:77,n:'Chilly Potato',c:'chilly-specials',p:99,op:0,d:'Honey chilli potato',r:4.8,rc:345,tag:'Popular',sp:2,e:'🔥',bg:'#FFFDE7'},
{id:78,n:'Chilly Manchurian',c:'chilly-specials',p:129,op:0,d:'Veg manchurian in chilly gravy',r:4.7,rc:198,tag:'Must Try',sp:3,e:'🔥',bg:'#FFEBEE'},
{id:79,n:'Schezwan Chilly Paneer',c:'chilly-specials',p:159,op:0,d:'Paneer in extra spicy schezwan',r:4.9,rc:278,tag:'New',sp:3,e:'🔥',bg:'#FBE9E7'}
];

const CATS = [
{id:'burgers',n:'Burgers',e:'🍔',ct:12},
{id:'wraps',n:'Wraps',e:'🌯',ct:8},
{id:'fries',n:'Fries',e:'🍟',ct:6},
{id:'sandwiches',n:'Sandwiches',e:'🥪',ct:10},
{id:'tikka-pav',n:'Tikka Pav',e:'🌭',ct:7},
{id:'quick-bites',n:'Quick Bites',e:'🧀',ct:9},
{id:'cold-drinks',n:'Cold Drinks',e:'🥤',ct:8},
{id:'mocktails',n:'Mocktails',e:'🍹',ct:6},
{id:'combos',n:'Combos',e:'🍽️',ct:5},
{id:'chilly-specials',n:'Chilly',e:'🔥',ct:8}
];

const TESTIMONIALS = [
{n:'Rahul K.',i:'RK',role:'Food Blogger',t:'Best veg burgers in Shela by far. The Crust Crunch is unreal — obsessed.',s:5},
{n:'Priya S.',i:'PS',role:'Regular Customer',t:'Tikka Pav here is dangerously addictive. Family favorite for late-night cravings.',s:5},
{n:'Ankit M.',i:'AM',role:'Verified Customer',t:'Family Feast combo is incredible value. Fresh, fast, and packed with flavor.',s:5},
{n:'Sneha P.',i:'SP',role:'College Student',t:'Open till 3 AM = my new lifesaver. Wraps are always fresh and full of taste.',s:5},
{n:'Karan D.',i:'KD',role:'Food Enthusiast',t:'Restaurant-quality chilly paneer. Hard to believe it\'s all 100% vegetarian!',s:5}
];